// Accurate API metadata for every Webverse tool.
// Each entry documents the REAL provider, method, authentication, input,
// output and response format as implemented in src/components.
// No credentials are stored here - only labels describing how auth works.

export const API_DETAILS = {
  weather: {
    id: "weather",
    provider: "WeatherAPI",
    method: "GET",
    authentication: "API key (query parameter)",
    apiKeyRequired: "Required",
    input: "City / location name",
    output: "Current conditions - temperature, feels like, humidity, wind, pressure, visibility, UV",
    response: "JSON",
    endpoint: "current.json - api.weatherapi.com/v1",
    purpose:
      "Retrieve live current-weather data for any city the user enters.",
    status: "Working (verified)",
    steps: [
      "The user types a city and submits the form.",
      "Webverse sends a GET request to WeatherAPI with the key and city.",
      "WeatherAPI returns JSON containing location and current sections.",
      "React extracts location.name/country and the current.* fields.",
      "The UI renders temperature, condition, wind, humidity, pressure, visibility and UV.",
    ],
    flow: [
      "User Input",
      "React",
      "GET Request",
      "WeatherAPI",
      "JSON Response",
      "React UI",
    ],
  },

  news: {
    id: "news",
    provider: "Configurable - Hacker News / Spaceflight News / NewsAPI",
    method: "GET",
    authentication: "None for keyless providers; NewsAPI needs an API key",
    apiKeyRequired: "Optional - NewsAPI only",
    input: "Category (general, business, entertainment, health, science, sports, technology) + provider",
    output: "Article list - title, source, date, description, image, link",
    response: "JSON",
    endpoint:
      "search_by_date (Hacker News) / articles (Spaceflight News) / top-headlines (NewsAPI)",
    purpose:
      "Fetch recent headlines for a chosen category from a selectable news provider.",
    status: "Working (keyless providers verified)",
    steps: [
      "The user picks a category and a data source.",
      "Webverse fetches articles from the selected provider.",
      "The provider returns a JSON list of articles.",
      "React normalizes title, source, date, description, image and link.",
      "Headlines render in an accordion that expands to show full details.",
    ],
    flow: [
      "Category + Provider",
      "React",
      "GET Request",
      "News Provider",
      "JSON (articles)",
      "React UI",
    ],
  },

  location: {
    id: "location",
    provider: "OpenCage",
    method: "GET",
    authentication: "API key (query parameter)",
    apiKeyRequired: "Required",
    input: "Place name - city, country or free text address",
    output:
      "Formatted address, components, coordinates, timezone and country flag",
    response: "JSON",
    endpoint: "Geocoding v1 - /geocode/v1/json (api.opencagedata.com)",
    purpose:
      "Geocode a place name into structured location data and coordinates.",
    status: "Needs a valid API key (OpenCage)",
    steps: [
      "The user types a place name and submits.",
      "Webverse sends a GET request to OpenCage with the query and key.",
      "OpenCage returns JSON with formatted address, components and geometry.",
      "React maps the fields into the info grid.",
      "A Google Maps link is built from the returned coordinates.",
    ],
    flow: [
      "Place name",
      "React",
      "GET Request",
      "OpenCage",
      "JSON Response",
      "React UI",
    ],
  },

  currency: {
    id: "currency",
    provider: "Frankfurter",
    method: "GET",
    authentication: "None",
    apiKeyRequired: "Not required",
    input: "Amount + From/To currency codes",
    output: "Converted amount",
    response: "JSON",
    endpoint: "currencies + latest (api.frankfurter.dev/v1)",
    purpose: "Convert an amount between currencies using live exchange rates.",
    status: "Working (verified)",
    steps: [
      "On mount, Webverse loads the currency list from Frankfurter.",
      "The user picks From/To currencies and enters an amount.",
      "Webverse requests /v1/latest with base and symbols.",
      "Frankfurter returns the rate for the target currency.",
      "React multiplies the amount by the rate and shows the result.",
    ],
    flow: [
      "Amount + Currency Codes",
      "React",
      "GET Request",
      "Frankfurter",
      "JSON (rates)",
      "React UI",
    ],
  },

  quotes: {
    id: "quotes",
    provider: "AnimeChan",
    method: "GET",
    authentication: "None",
    apiKeyRequired: "Not required",
    input: "None - random quote by default",
    output: "Quote text, anime title and character name",
    response: "JSON",
    endpoint: "Random quote - /v1/quotes/random (animechan.io)",
    purpose: "Fetch a random anime quote.",
    status: "Working (verified)",
    steps: [
      "The user clicks the Generate New Quote button.",
      "Webverse requests a random quote from AnimeChan.",
      "AnimeChan returns JSON with quote, anime and character.",
      "React extracts the three fields into state.",
      "The quote, anime and character are displayed.",
    ],
    flow: [
      "Button click",
      "React",
      "GET Request",
      "AnimeChan",
      "JSON Response",
      "React UI",
    ],
  },

  jokes: {
    id: "jokes",
    provider: "JokeAPI",
    method: "GET",
    authentication: "None",
    apiKeyRequired: "Not required",
    input: "None - random; blacklist filters out nsfw/religious/political/racist/sexist/explicit",
    output: "A single-line joke",
    response: "JSON",
    endpoint: "Single joke - /joke/Any (v2.jokeapi.dev)",
    purpose: "Fetch a random joke filtered to stay clean.",
    status: "Working (verified)",
    steps: [
      "The user clicks the Get Random Joke button.",
      "Webverse requests a joke from JokeAPI with blacklist filters and type=single.",
      "JokeAPI returns JSON containing the joke text.",
      "React stores the joke in state.",
      "The joke text is displayed.",
    ],
    flow: [
      "Button click",
      "React",
      "GET Request",
      "JokeAPI",
      "JSON Response",
      "React UI",
    ],
  },

  textspeech: {
    id: "textspeech",
    provider: "Web Speech API (built into the browser)",
    method: "Local (browser service)",
    authentication: "None",
    apiKeyRequired: "Not required",
    input: "Text, selected voice and speech rate",
    output: "Audio speech playback",
    response: "Audio",
    endpoint:
      "No HTTP endpoint - window.speechSynthesis (Web Speech API)",
    purpose:
      "Convert text to speech locally using the browser's built-in voices.",
    status: "Works offline - browser built-in",
    steps: [
      "The user types text, picks a voice and adjusts the speech rate.",
      "React creates a SpeechSynthesisUtterance from the text.",
      "The browser's Web Speech API synthesizes the speech locally.",
      "The audio plays through the device speakers.",
      "No HTTP request or API key is involved.",
    ],
    flow: [
      "User Text",
      "React",
      "Web Speech API",
      "Browser Voices",
      "Audio Playback",
    ],
  },

  generateimg: {
    id: "generateimg",
    provider: "OpenAI",
    method: "POST",
    authentication: "API key (Bearer token)",
    apiKeyRequired: "Required",
    input: "Text prompt + model (gpt-image-1), size (1024x1024), count (1)",
    output: "Generated image as base64 data or a hosted URL",
    response: "JSON",
    endpoint: "Images - /v1/images/generations (api.openai.com)",
    purpose: "Generate an image from a text description using AI.",
    status: "Needs a valid API key (OpenAI)",
    steps: [
      "The user types a prompt and clicks Create.",
      "Webverse POSTs the prompt to OpenAI with a Bearer API key.",
      "OpenAI generates the image server-side and returns it as base64 or a URL.",
      "React renders the returned image in the preview box.",
      "No image processing happens in the browser.",
    ],
    flow: [
      "Prompt",
      "React",
      "POST Request",
      "OpenAI",
      "Image Response",
      "React UI",
    ],
  },

  prayertimes: {
    id: "prayertimes",
    provider: "Aladhan",
    method: "GET",
    authentication: "None",
    apiKeyRequired: "Not required",
    input: "Egyptian city (the app appends \",Egypt\" to the address)",
    output: "Daily prayer timings (Fajr to Isha) and the readable date",
    response: "JSON",
    endpoint: "Timings - /v1/timingsByAddress (api.aladhan.com)",
    purpose:
      "Fetch daily Islamic prayer times for cities in Egypt using method 8.",
    status: "Working (verified)",
    steps: [
      "The user selects a city from the list.",
      "Webverse requests Aladhan with the city address and method=8.",
      "Aladhan returns JSON timing data for the day.",
      "React stores the timings and readable date.",
      "Times from Fajr to Isha are listed on the page.",
    ],
    flow: [
      "City (Egypt)",
      "React",
      "GET Request",
      "Aladhan",
      "JSON (timings)",
      "React UI",
    ],
  },

  uploadimg: {
    id: "uploadimg",
    provider: "Cloudinary",
    method: "POST",
    authentication: "None (unsigned upload preset)",
    apiKeyRequired: "Not required",
    input: "Image file + upload preset + cloud name (multipart form data)",
    output: "Hosted image URL (secure_url)",
    response: "JSON",
    endpoint:
      "Image upload - /v1_1/{cloud_name}/image/upload (api.cloudinary.com)",
    purpose: "Upload a local image to Cloudinary and get a shareable URL.",
    status: "Endpoint reachable (upload needs a selected file)",
    steps: [
      "The user selects a local image file.",
      "Webverse builds form data with the file, upload preset and cloud name.",
      "Cloudinary receives the multipart POST and hosts the image.",
      "Cloudinary returns JSON with the secure image URL.",
      "React displays a preview and the hosted image URL.",
    ],
    flow: [
      "Image file",
      "React",
      "POST Request",
      "Cloudinary",
      "JSON (URL)",
      "React UI",
    ],
  },
};

export const getApiDetails = (id) => API_DETAILS[id] || null;